article:
  repository:
    host: "http://cmts3.f4.htw-berlin.de:8000"

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: isys

---
spring:
  profiles: heroku

spring:
  data:
    mongodb:
      host:
      uri: uri: ${MONGODB_URI:none}
