@startuml

skinparam shadowing false
skinparam backgroundColor #2e3037
skinparam arrowColor #39c0ba
skinparam defaultFontColor #39c0ba

skinparam activity {
  StartColor #39c0ba
  EndColor #39c0ba
  BarColor #39c0ba
  BackgroundColor #2e3037
  BorderColor #877dcd
  FontName Courier
  DiamondBackgroundColor #2e3037
  DiamondBorderColor #877dcd
}

skinparam note {
  BackgroundColor #2e3037
  BorderColor #877dcd
  FontName Courier
}

start
  :load Articles from DB;
	:create Shingles;
	:MinHash;
	:LSH;
    if (Similarity of two Articles > Threshold) then (yes)
      :mark as duplicate;
    else
      ->no; 
    endif
	:store filtered Articles;
stop
@enduml
